SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__acctime__ret__scalar, acc_time)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__armorypoints__ret__scalar, armory_points)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__benchmark__ret__scalar, benchmark)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__blufor__ret__side, blufor)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__briefingname__ret__string, briefing_name)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__buldozer_isenabledroaddiag__ret__bool, buldozer_is_enabled_road_diag)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__buldozer_reloadopermap__ret__nothing, buldozer_reload_oper_map)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__cadetmode__ret__bool, cadet_mode)
SIMPLE_NULAR_FUNC_OBJECT(__sqf::nular__cameraon__ret__object, camera_on)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__cameraview__ret__string, camera_view)
SIMPLE_NULAR_FUNC_CONFIG(__sqf::nular__campaignconfigfile__ret__config, campaign_config_file)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__cheatsenabled__ret__bool, cheats_enabled)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__civilian__ret__side, civilian)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__clearforcesrtd__ret__nothing, clear_forces_rtd)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__clearitempool__ret__nothing, clear_item_pool)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__clearmagazinepool__ret__nothing, clear_magazine_pool)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__clearradio__ret__nothing, clear_radio)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__clearweaponpool__ret__nothing, clear_weapon_pool)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__clientowner__ret__scalar, client_owner)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__commandingmenu__ret__string, commanding_menu)
SIMPLE_NULAR_FUNC_CONFIG(__sqf::nular__configfile__ret__config, config_file)
SIMPLE_NULAR_FUNC_CONFIG(__sqf::nular__confignull__ret__config, config_null)
SIMPLE_NULAR_FUNC_CONTROL(__sqf::nular__controlnull__ret__control, control_null)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__copyfromclipboard__ret__string, copy_from_clipboard)
SIMPLE_NULAR_FUNC_OBJECT(__sqf::nular__curatorcamera__ret__object, curator_camera)
SIMPLE_NULAR_FUNC_OBJECT(__sqf::nular__curatormouseover__ret__object, curator_mouse_over)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__current3denoperation__ret__string, current_3denoperation)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__currentchannel__ret__scalar, current_channel)
SIMPLE_NULAR_FUNC_NAMESPACE(__sqf::nular__currentnamespace__ret__namespace, current_namespace)
SIMPLE_NULAR_FUNC_OBJECT(__sqf::nular__cursortarget__ret__object, cursor_target)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__daytime__ret__scalar, day_time)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__diag_fps__ret__scalar, diag_fps)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__diag_fpsmin__ret__scalar, diag_fpsmin)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__diag_frameno__ret__scalar, diag_frameno)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__diag_ticktime__ret__scalar, diag_tick_time)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__dialog__ret__bool, dialog)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__didjip__ret__bool, did_jip)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__difficulty__ret__scalar, difficulty)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__difficultyenabledrtd__ret__bool, difficulty_enabled_rtd)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__disabledebriefingstats__ret__nothing, disable_debriefing_stats)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__disableserialization__ret__nothing, disable_serialization)
SIMPLE_NULAR_FUNC_DISPLAY(__sqf::nular__displaynull__ret__display, display_null)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__distributionregion__ret__scalar, distribution_region)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__east__ret__side, east)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__enableenddialog__ret__nothing, enable_end_dialog)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__endloadingscreen__ret__nothing, end_loading_screen)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__estimatedendservertime__ret__scalar, estimated_end_server_time)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__exit__ret__nothing, exit)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__finishmissioninit__ret__nothing, finish_mission_init)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__fog__ret__scalar, fog)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__fogforecast__ret__scalar, fog_forecast)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__forceend__ret__nothing, force_end)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__forceweatherchange__ret__nothing, force_weather_change)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__freelook__ret__bool, free_look)
SIMPLE_NULAR_FUNC_OBJECT(__sqf::nular__get3dencamera__ret__object, get_3dencamera)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__get3deniconsvisible__ret__bool, get_3denicons_visible)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__get3denlinesvisible__ret__bool, get_3denlines_visible)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__getclientstate__ret__string, get_client_state)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__getelevationoffset__ret__scalar, get_elevation_offset)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__getremotesensorsdisabled__ret__bool, get_remote_sensors_disabled)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__getshadowdistance__ret__scalar, get_shadow_distance)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__gettotaldlcusagetime__ret__scalar, get_total_dlcusage_time)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__groupiconselectable__ret__bool, group_icon_selectable)
SIMPLE_NULAR_FUNC_GROUP(__sqf::nular__grpnull__ret__group, grp_null)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__gusts__ret__scalar, gusts)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__halt__ret__nothing, halt)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__hasinterface__ret__bool, has_interface)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__hcshownbar__ret__bool, hc_shown_bar)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__humidity__ret__scalar, humidity)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__independent__ret__side, independent)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__initambientlife__ret__nothing, init_ambient_life)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__is3den__ret__bool, is_3den)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__is3denmultiplayer__ret__bool, is_3denmultiplayer)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__isautotest__ret__bool, is_autotest)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__isdedicated__ret__bool, is_dedicated)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__isfilepatchingenabled__ret__bool, is_file_patching_enabled)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__isinstructorfigureenabled__ret__bool, is_instructor_figure_enabled)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__ismultiplayer__ret__bool, is_multiplayer)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__ispipenabled__ret__bool, is_pip_enabled)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__isserver__ret__bool, is_server)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__issteammission__ret__bool, is_steam_mission)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__isstreamfriendlyuienabled__ret__bool, is_stream_friendly_uienabled)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__isstressdamageenabled__ret__bool, is_stress_damage_enabled)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__istuthintsenabled__ret__bool, is_tut_hints_enabled)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__language__ret__string, language)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__lightnings__ret__scalar, lightnings)
SIMPLE_NULAR_FUNC_TEXT(__sqf::nular__linebreak__ret__text, line_break)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__loadgame__ret__nothing, load_game)
SIMPLE_NULAR_FUNC_LOCATION(__sqf::nular__locationnull__ret__location, location_null)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__logentities__ret__nothing, log_entities)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__mapanimclear__ret__nothing, map_anim_clear)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__mapanimcommit__ret__nothing, map_anim_commit)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__mapanimdone__ret__bool, map_anim_done)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__markasfinishedonsteam__ret__bool, mark_as_finished_on_steam)
SIMPLE_NULAR_FUNC_CONFIG(__sqf::nular__missionconfigfile__ret__config, mission_config_file)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__missiondifficulty__ret__scalar, mission_difficulty)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__missionname__ret__string, mission_name)
SIMPLE_NULAR_FUNC_NAMESPACE(__sqf::nular__missionnamespace__ret__namespace, mission_namespace)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__moonintensity__ret__scalar, moon_intensity)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__musicvolume__ret__scalar, music_volume)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__nextweatherchange__ret__scalar, next_weather_change)
SIMPLE_NULAR_FUNC_ANY(__sqf::nular__nil__ret__any, nil)
SIMPLE_NULAR_FUNC_OBJECT(__sqf::nular__objnull__ret__object, obj_null)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__opencuratorinterface__ret__nothing, open_curator_interface)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__opfor__ret__side, opfor)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__overcast__ret__scalar, overcast)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__overcastforecast__ret__scalar, overcast_forecast)
SIMPLE_NULAR_FUNC_NAMESPACE(__sqf::nular__parsingnamespace__ret__namespace, parsing_namespace)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__particlesquality__ret__scalar, particles_quality)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__pi__ret__scalar, pi)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__pixelh__ret__scalar, pixel_h)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__pixelw__ret__scalar, pixel_w)
SIMPLE_NULAR_FUNC_OBJECT(__sqf::nular__player__ret__object, player)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__playerrespawntime__ret__scalar, player_respawn_time)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__playerside__ret__side, player_side)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__profilename__ret__string, profile_name)
SIMPLE_NULAR_FUNC_NAMESPACE(__sqf::nular__profilenamespace__ret__namespace, profile_namespace)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__profilenamesteam__ret__string, profile_name_steam)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__radiovolume__ret__scalar, radio_volume)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__rain__ret__scalar, rain)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__rainbow__ret__scalar, rainbow)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__resetcamshake__ret__nothing, reset_cam_shake)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__resistance__ret__side, resistance)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__reversedmousey__ret__bool, reversed_mouse_y)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__runinitscript__ret__nothing, run_init_script)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__safezoneh__ret__scalar, safe_zone_h)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__safezonew__ret__scalar, safe_zone_w)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__safezonewabs__ret__scalar, safe_zone_wabs)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__safezonex__ret__scalar, safe_zone_x)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__safezonexabs__ret__scalar, safe_zone_xabs)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__safezoney__ret__scalar, safe_zone_y)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__savegame__ret__nothing, save_game)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__savejoysticks__ret__nothing, save_joysticks)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__saveprofilenamespace__ret__nothing, save_profile_namespace)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__savingenabled__ret__bool, saving_enabled)
SIMPLE_NULAR_FUNC_SCRIPT(__sqf::nular__scriptnull__ret__script, script_null)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__selectnoplayer__ret__nothing, select_no_player)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__servername__ret__string, server_name)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__servertime__ret__scalar, server_time)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownartillerycomputer__ret__bool, shown_artillery_computer)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownchat__ret__bool, shown_chat)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__showncompass__ret__bool, shown_compass)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__showncuratorcompass__ret__bool, shown_curator_compass)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__showngps__ret__bool, shown_gps)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownmap__ret__bool, shown_map)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownpad__ret__bool, shown_pad)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownradio__ret__bool, shown_radio)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownuavfeed__ret__bool, shown_uavfeed)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownwarrant__ret__bool, shown_warrant)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__shownwatch__ret__bool, shown_watch)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__sideenemy__ret__side, side_enemy)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__sidefriendly__ret__side, side_friendly)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__sidelogic__ret__side, side_logic)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__sideunknown__ret__side, side_unknown)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__simulweathersync__ret__nothing, simul_weather_sync)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__slingloadassistantshown__ret__bool, sling_load_assistant_shown)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__soundvolume__ret__scalar, sound_volume)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__sunormoon__ret__scalar, sun_or_moon)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__systemofunits__ret__scalar, system_of_units)
SIMPLE_NULAR_FUNC_TASK(__sqf::nular__tasknull__ret__task, task_null)
SIMPLE_NULAR_FUNC_TEAM_MEMBER(__sqf::nular__teammembernull__ret__team_member, team_member_null)
SIMPLE_NULAR_FUNC_NOTHING(__sqf::nular__teamswitch__ret__nothing, team_switch)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__teamswitchenabled__ret__bool, team_switch_enabled)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__time__ret__scalar, time)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__timemultiplier__ret__scalar, time_multiplier)
SIMPLE_NULAR_FUNC_NAMESPACE(__sqf::nular__uinamespace__ret__namespace, ui_namespace)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__viewdistance__ret__scalar, view_distance)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__visiblecompass__ret__bool, visible_compass)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__visiblegps__ret__bool, visible_gps)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__visiblemap__ret__bool, visible_map)
SIMPLE_NULAR_FUNC_BOOL(__sqf::nular__visiblewatch__ret__bool, visible_watch)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__waves__ret__scalar, waves)
SIMPLE_NULAR_FUNC_SIDE(__sqf::nular__west__ret__side, west)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__winddir__ret__scalar, wind_dir)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__windstr__ret__scalar, wind_str)
SIMPLE_NULAR_FUNC_STRING(__sqf::nular__worldname__ret__string, world_name)
SIMPLE_NULAR_FUNC_SCALAR(__sqf::nular__worldsize__ret__scalar, world_size)


/*
#define SIMPLE_NULAR_FUNC_ANY(ptr, fnc)
#define SIMPLE_NULAR_FUNC_BOOL(ptr, fnc)
#define SIMPLE_NULAR_FUNC_CONFIG(ptr, fnc)
#define SIMPLE_NULAR_FUNC_CONTROL(ptr, fnc)
#define SIMPLE_NULAR_FUNC_DISPLAY(ptr, fnc)
#define SIMPLE_NULAR_FUNC_GROUP(ptr, fnc)
#define SIMPLE_NULAR_FUNC_LOCATION(ptr, fnc)
#define SIMPLE_NULAR_FUNC_NAMESPACE(ptr, fnc)
#define SIMPLE_NULAR_FUNC_NOTHING(ptr, fnc)
#define SIMPLE_NULAR_FUNC_OBJECT(ptr, fnc)
#define SIMPLE_NULAR_FUNC_SCALAR(ptr, fnc)
#define SIMPLE_NULAR_FUNC_SCRIPT(ptr, fnc)
#define SIMPLE_NULAR_FUNC_SIDE(ptr, fnc)
#define SIMPLE_NULAR_FUNC_STRING(ptr, fnc)
#define SIMPLE_NULAR_FUNC_TASK(ptr, fnc)
#define SIMPLE_NULAR_FUNC_TEAM_MEMBER(ptr, fnc)
#define SIMPLE_NULAR_FUNC_TEXT(ptr, fnc)
*/